Added parameter to ignore NPM
Varying-Vagrant-Vagrants/custom-site-template-develop pull request #32
Opened 2022-03-08 17:42 UTC by Mte90

Ref: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2584

2022-03-09 13:44 UTC, tomjn requested changes
I wonder if we should also do some UX changes, in particular making `npm` failure non-blocking, so if `npm` fails then we can catch and report this to the user and mention the new flags so it isn't a mystery?

Maybe not this but something similar:

> `npm` failed to run, check the site log for output in the provisioner logs folder. You may want to run `npm` commands on the host and disable npm during provisioning. We'll continue provisioning but some things may not work.

2022-03-09 13:44 UTC, tomjn commented on provision/vvv-init.sh
> +fi
an else statement reporting that it was skipped would be good here

2022-03-09 13:44 UTC, tomjn commented on provision/vvv-init.sh
> +fi
Perhaps separate flags for grunt and npm?

2022-03-09 14:00 UTC, Mte90 commented on provision/vvv-init.sh
> +fi
Grunt packages are in the same package.json file so it isn't possible to install just them.

2022-03-09 14:02 UTC, Mte90 commented
> I wonder if we should also do some UX changes, in particular making `npm` failure non-blocking, so if `npm` fails then we can catch and report this to the user and mention the new flags so it isn't a mystery?

I don't know if it is easy to track NPM errors or if return a specific exit code

2022-03-09 16:35 UTC, Mte90 commented
I see also another issue in the tests config file that is not filled with the VVV data.
I will update this PR.

2022-03-09 17:10 UTC, tomjn commented
True but I was referring to running the grunt build

On Wed, 9 Mar 2022 at 14:00, Daniele Scasciafratte ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In provision/vvv-init.sh
> <https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop/pull/32#discussion_r822677017>
> :
>
> > +if [[ "${NPM}" == "true" ]]; then
> +  try_npm_install
> +  try_grunt_build
> +fi
>
> Grunt packages are in the same package.json file so it isn't possible to
> install just them.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop/pull/32#discussion_r822677017>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAOLZ23JM2YD7WATQSHENDU7CVIJANCNFSM5QHBCZGQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because your review was requested.Message ID:
> <Varying-Vagrant-Vagrants/custom-site-template-develop/pull/32/review/904400326
> @github.com>
>

2022-03-09 17:10 UTC, tomjn commented
Just did the npm commands return a good or a bad code, we don’t need to be
any more specific than that

On Wed, 9 Mar 2022 at 14:03, Daniele Scasciafratte ***@***.***>
wrote:

> I wonder if we should also do some UX changes, in particular making npm
> failure non-blocking, so if npm fails then we can catch and report this
> to the user and mention the new flags so it isn't a mystery?
>
> I don't know if it is easy to track NPM errors or if return a specific
> exit code
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop/pull/32#issuecomment-1062952118>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAOLZZ4VOKAFB2ZGEG2FIDU7CVRPANCNFSM5QHBCZGQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because your review was requested.Message ID:
> <Varying-Vagrant-Vagrants/custom-site-template-develop/pull/32/c1062952118
> @github.com>
>

2022-03-09 17:12 UTC, Mte90 commented
You are right, I checked now the code and I saw that grunt was executed twice in the provision.
The last commit should fix everything, I am testing it.

2022-11-16 13:57 UTC, Mte90 commented
@tomjn can you check now this pr?

2022-11-16 14:17 UTC, tomjn approved these changes

2022-11-16 14:17 UTC, merged